
version: 2

sources:
    - name: staging
      database: fluent-tea-338517
      schema: trips_data_all
      location: europe-west6

      # loaded_at_field: record_loaded_at
      tables:
        - name: green_tripdata
        - name: yellow_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}